---
# handlers file for roles/prometheus
- name: restart_prometheus
  systemd:
    name: prometheus
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: reload_prometheus
  uri:
    url: http://prometheus:9090/
    method: POST
    status_code: 302
  register: __result
  until: __result.status == 302
  retries: 120
  delay: 10
