---
# handlers file for roles/prometheus
- name: restart_prometheus
  systemd:
    name: prometheus
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: reload_prometheus
  uri:
    url: prometheus:9100/metrics
    method: GET
    status_code: 200
  register: __result
  until: __result.status == 200
  retries: 120
  delay: 10
