---
# tasks file for roles/backup
- name: install yc
  shell:
    cmd: curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash

- name: configure yc
  shell:
    cmd: |
      source "/home/ubuntu/.bashrc"
      yc config profile create netology-diplom
      exit 0

- name: copy backup script
  template: src=backup-netology.sh.j2 dest=/usr/bin/backup-netology.sh
  become: true

- name: make script exec
  file:
    path: /usr/bin/backup-netology.sh
    mode: '0771'
  become: true

- name: make cron task
  cron:
    name: "Daily snapshot"
    job: /usr/bin/backup-netology.sh
    minute: "0"
    hour: "0"
