---
# tasks file for roles/prometheus
- name: update and install prometheus
  apt:
    pkg:
    - prometheus
    - python
    - python3
    update_cache: yes

- name: prometheus args
  template:
    src: prometheus.j2
    dest: /etc/default/prometheus
    mode: 0644
    owner: root
    group: root
  notify: restart_prometheus

- name: prometheus configuration file
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_dir_configuration }}/prometheus.yml"
    mode: 0755
    owner: prometheus
    group: prometheus
  notify: reload_prometheus

- name: start prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes
