---
# tasks file for roles/kibana
- name: APT - Add elastic repo key
  apt_key: url="https://artifacts.elastic.co/GPG-KEY-elasticsearch"

#- name: Add Elastic repo into source list
#  apt_repository:
#    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
#    state: present

- name: Add repo to source list
  shell: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" >> /etc/apt/sources.list.d/kibana.list
  become: true

- name: Install kibana
  apt: name=kibana update_cache=yes
  become: true

- name: Copy config
  template: src=kibanaConf.j2 dest=/etc/kibana/kibana.yml
 
- name: Force systemd to reread configs
  systemd: daemon_reload=yes
  become: true
 
- name: Enable kibana.service
  systemd:
    name: kibana.service
    enabled: yes
  become: true
 
- name: Start kibana.service
  systemd: name=kibana.service state=restarted
  become: true
